### PR TITLE
fix(service): added fetch options

### LINKED ISSUE #4: bug(horoscope-service): headers are not specified
**Describe the bug**

The service does not send browser headers such as the `accept`, `accept-encoding`, `accept-language`, `upgrade-insecure-requests`, `user-agent`, and others.

https://github.com/skyra-project/saelem/blob/5d9bf868a7908d7d798988e55ba83c470cf61db0/src/services/HoroscopeService.ts#L17

**To Reproduce**

1. Make a request.
2. Notice how the service barely sends any headers.

**Expected behavior**

It should send headers to emulate the behaviour of a regular user.

**Screenshots**

N/a.

**Additional context**

N/a.

### PR DESCRIPTION
**Pull request by Favna**
closes #4﻿

Headers based on the values on the site
image

### CODE REVIEW

File: src/services/HoroscopeService.ts [hunk 1]
```diff
@@ -1,20 +1,33 @@
...
 import type sunsigns from '../utils/sunsigns';
 import { toTitleCase } from '../utils/utils';
 
 export default class HoroscopeService {
 	#baseSeletor = '.sign-hero__horoscope-wrapper > .day-tabs-content--sign-page';
+	#fetchOptions: RequestInit = {
+		headers: {
+			accept: '*/*',
+			'accept-encoding': 'gzip, deflate, br',
+			'accept-language': 'en-US,en;q=0.9,nl;q=0.8',
```
Comment (kyranet) [inline src/services/HoroscopeService.ts:15]: Based on https://www.w3.org/International/O-charset-lang.html, it'd make sense if the secondary preferred language were German, since the VPS is hosted there.
```suggestion
			'accept-language': 'en-US,en;q=0.9,de;q=0.8',
```
